name: Deploy

on:
  push:
    branches:
      -main

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      -uses: action/checkout@v2
      -uses: akhileshns/heroku-deploy@v3.12.12 ## this is the action
       with:
        heroku_api_key:
        heroku_api_name:
        heroku_api_name:
